2024-08-26 16:59:10,550 - ERROR - Ошибка при отправке документа 'Заявление на увольнение.docx': [Errno 2] No such file or directory: 'C:\\Users\\s_shilovvas\\PycharmProjects\\pythonProject1\\Заявление на увольнение.docx'
2024-08-26 16:59:14,136 - ERROR - Ошибка при отправке документа 'Заявление на увольнение.docx': [Errno 2] No such file or directory: 'C:\\Users\\s_shilovvas\\PycharmProjects\\pythonProject1\\Заявление на увольнение.docx'
2024-08-26 16:59:15,030 - ERROR - Ошибка при отправке документа 'Заявление на отзыв заявления об увольнении.docx': [Errno 2] No such file or directory: 'C:\\Users\\s_shilovvas\\PycharmProjects\\pythonProject1\\Заявление на отзыв заявления об увольнении.docx'
2024-08-26 17:45:09,124 - ERROR - Ошибка при запуске бота: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
2024-08-27 10:16:00,408 - ERROR - Ошибка при отправке утреннего сообщения: 'int' object is not iterable
2024-08-27 10:16:00,463 - ERROR - Ошибка при отправке утреннего сообщения: 'int' object is not iterable
2024-08-27 10:16:00,463 - ERROR - Ошибка при отправке утреннего сообщения: 'int' object is not iterable
2024-08-27 10:16:00,463 - ERROR - Ошибка при отправке утреннего сообщения: 'int' object is not iterable
2024-08-27 10:16:00,463 - ERROR - Ошибка при отправке утреннего сообщения: 'int' object is not iterable
2024-08-27 10:18:00,656 - ERROR - Ошибка при отправке утреннего сообщения: 'int' object is not iterable
2024-08-27 10:18:00,657 - ERROR - Ошибка при отправке утреннего сообщения: 'int' object is not iterable
2024-08-27 10:18:00,657 - ERROR - Ошибка при отправке утреннего сообщения: 'int' object is not iterable
2024-08-27 10:18:00,658 - ERROR - Ошибка при отправке утреннего сообщения: 'int' object is not iterable
2024-08-27 10:18:00,658 - ERROR - Ошибка при отправке утреннего сообщения: 'int' object is not iterable
2024-08-27 15:42:44,522 - ERROR - Ошибка при обработке неизвестной команды: TeleBot.send_message() missing 2 required positional arguments: 'chat_id' and 'text'
2024-08-27 15:50:54,390 - ERROR - Ошибка при обработке неизвестной команды: TeleBot.send_message() missing 2 required positional arguments: 'chat_id' and 'text'
2024-08-27 16:00:41,189 - ERROR - Ошибка при обработке неизвестной команды: TeleBot.send_message() missing 2 required positional arguments: 'chat_id' and 'text'
2024-08-27 16:01:04,034 - ERROR - Ошибка при обработке неизвестной команды: TeleBot.send_message() missing 2 required positional arguments: 'chat_id' and 'text'
2024-08-27 16:03:50,604 - ERROR - Ошибка при обработке неизвестной команды: TeleBot.send_message() missing 2 required positional arguments: 'chat_id' and 'text'
2024-08-27 16:15:08,684 - ERROR - Ошибка при обработке неизвестной команды: TeleBot.send_message() missing 2 required positional arguments: 'chat_id' and 'text'
2024-08-27 16:17:02,895 - ERROR - Ошибка при обработке неизвестной команды: TeleBot.send_message() missing 2 required positional arguments: 'chat_id' and 'text'
2024-08-28 13:27:03,057 - ERROR - Ошибка при отправке ссылки в группу -1004269879858: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
2024-08-28 13:29:59,896 - ERROR - Ошибка при обработке неизвестной команды: TeleBot.send_message() missing 2 required positional arguments: 'chat_id' and 'text'
2024-08-28 13:42:14,223 - ERROR - Ошибка при отправке ссылок: Expecting value: line 1 column 1 (char 0)
2024-08-28 13:42:14,583 - ERROR - Ошибка при обновлении ссылок: Expecting value: line 1 column 1 (char 0)
2024-08-28 13:43:54,233 - ERROR - Ошибка при отправке ссылок: Expecting value: line 1 column 1 (char 0)
2024-08-28 13:43:54,685 - ERROR - Ошибка при обновлении ссылок: Expecting value: line 1 column 1 (char 0)
2024-08-28 13:46:29,004 - ERROR - Ошибка при обработке неизвестной команды: TeleBot.send_message() missing 2 required positional arguments: 'chat_id' and 'text'
2024-08-28 13:48:02,824 - ERROR - Ошибка при обработке неизвестной команды: TeleBot.send_message() missing 2 required positional arguments: 'chat_id' and 'text'
2024-08-28 13:49:18,540 - ERROR - Ошибка при обработке неизвестной команды: TeleBot.send_message() missing 2 required positional arguments: 'chat_id' and 'text'
2024-08-28 13:50:13,728 - ERROR - Ошибка при обработке неизвестной команды: TeleBot.send_message() missing 2 required positional arguments: 'chat_id' and 'text'
2024-08-28 13:50:21,930 - ERROR - Ошибка чтения JSON файла: Expecting value: line 1 column 1 (char 0)
2024-08-28 13:50:22,299 - ERROR - Ошибка чтения JSON файла: Expecting value: line 1 column 1 (char 0)
2024-08-28 13:52:37,827 - ERROR - Ошибка при обработке неизвестной команды: TeleBot.send_message() missing 2 required positional arguments: 'chat_id' and 'text'
2024-08-28 13:57:00,120 - ERROR - Ошибка чтения JSON файла: Expecting value: line 1 column 1 (char 0)
2024-08-28 13:57:00,763 - ERROR - Ошибка чтения JSON файла: Expecting value: line 1 column 1 (char 0)
2024-08-28 13:58:23,016 - ERROR - Ошибка чтения JSON файла: Expecting value: line 1 column 1 (char 0)
2024-08-28 13:58:23,437 - ERROR - Ошибка чтения JSON файла: Expecting value: line 1 column 1 (char 0)
2024-08-28 15:33:44,647 - ERROR - Ошибка при обработке неизвестной команды: TeleBot.send_message() missing 2 required positional arguments: 'chat_id' and 'text'
2024-08-28 15:35:38,390 - ERROR - Ошибка при обработке неизвестной команды: TeleBot.send_message() missing 2 required positional arguments: 'chat_id' and 'text'
2024-08-28 16:05:48,704 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-28 16:05:48,706 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 1225, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 687, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 659, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-28 16:05:52,038 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-28 16:05:52,039 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 1225, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 687, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 659, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-28 16:05:52,367 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-28 16:05:52,368 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 1225, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 687, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 659, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-28 16:05:55,795 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-28 16:05:55,795 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 1225, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 687, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 659, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-28 16:05:55,936 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-28 16:05:55,936 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 1225, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 687, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 659, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-28 16:05:59,500 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-28 16:05:59,501 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 1225, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 687, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 659, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-28 16:05:59,824 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-28 16:05:59,824 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 1225, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 687, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 659, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-28 16:05:59,851 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-28 16:05:59,851 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 1225, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 687, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 659, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-28 16:06:03,913 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-28 16:06:03,913 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 1225, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 687, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 659, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-28 16:06:04,478 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-28 16:06:04,478 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 1225, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 687, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 659, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-28 16:06:04,929 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-28 16:06:04,929 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 1225, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 687, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 659, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-28 16:06:08,544 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-28 16:06:08,544 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 1225, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 687, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 659, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-28 16:06:12,622 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-28 16:06:12,623 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 1225, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 687, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 659, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-28 16:06:16,778 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-28 16:06:16,778 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 1225, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 687, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 659, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-28 16:06:20,688 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-28 16:06:20,689 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 1225, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 687, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 659, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-28 16:06:24,014 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-28 16:06:24,015 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 1225, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 687, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 659, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-28 16:06:24,851 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-28 16:06:24,851 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 1225, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 687, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 659, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-28 16:06:28,414 - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-28 16:06:28,415 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 1225, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 687, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\__init__.py", line 659, in get_updates
    json_updates = apihelper.get_updates(
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 330, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\s_shilovvas\PycharmProjects\pythonProject1\venv\lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2024-08-28 16:08:54,252 - ERROR - Ошибка при обработке неизвестной команды: TeleBot.send_message() missing 2 required positional arguments: 'chat_id' and 'text'
